const cors = require("cors");
const dotenv = require("dotenv");
const express = require("express");
const mongoose = require("mongoose");
const bodyParser = require("body-parser");
const connectDB = require("./config/config");
const signuproutes = require("./router/signup");
const loginRoutes = require("./router/login");
const profileRoutes = require("./router/profile");
const projectRoutes = require("./router/project");
const aboutRoutes = require("./router/about");
const termsRoutes = require("./router/terms");
const contactRoutes = require("./router/contact");
const policyRoutes = require("./router/policy");
const faqRoutes = require("./router/faq");
const contactsRoutes = require("./router/contacts");
const notificationRoutes=require('./router/notification');
const app = express();
dotenv.config();
connectDB();
app.use(cors());
app.use(bodyParser.json());
app.use("/", signuproutes);
app.use("/", loginRoutes);
app.use("/", profileRoutes);
app.use("/", projectRoutes);
app.use("/", aboutRoutes);
app.use("/", termsRoutes);
app.use("/", contactRoutes);
app.use("/", policyRoutes);
app.use("/", faqRoutes);
app.use("/", contactsRoutes);
app.use("/", notificationRoutes);
const port = process.env.PORT || 5001;
app.listen(port, () => {
  console.log(`IFP's Server is running on port ${port}`);
});
