import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
//@ts-ignore
import Header from "../Header/Header";
import Footer from "../Footer/Footer";
import family from "../../assets/fam 1.jpg";
import { PiUsersThreeBold } from "react-icons/pi";
import { Link } from "react-router-dom";
const FamilyPortal = () => {
    return (_jsxs("div", { className: "d-flex align-items-center flex-column", children: [_jsx("div", { className: "mb-5", children: _jsx(Header, {}) }), _jsxs("div", { className: "container-fluid px-3 mt-4", children: [_jsx("h3", { className: "mt-5", children: "Family Portal" }), _jsxs("div", { children: [_jsx("img", { src: family, className: "w-100 h-auto", alt: "" }), _jsx("p", { className: "fw-medium", children: "Welcome to the family portal where you are able to view all your family members" }), _jsxs("div", { children: [_jsxs("div", { className: "d-flex justify-content-between align-items-center mt-3", children: [_jsxs("div", { children: [_jsx("h5", { className: "fw-semibold text-success mb-1", children: "NGABO Oreste" }), _jsx("p", { className: "mb-0", children: "Family leader" })] }), _jsx("div", { children: _jsx("button", { className: "btn btn-success w-auto px-3 pt-2 pb-2", children: "Update family" }) })] }), _jsxs("div", { className: "d-flex justify-content-start align-items-center bg-success-subtle p-2 text-center rounded-5 w-50 mt-3", children: [_jsx(PiUsersThreeBold, { size: 33, className: "ms-3" }), " ", _jsx("span", { className: "mx-3 fs-6", children: "5 members" })] }), _jsxs("div", { className: "mt-3", children: [_jsx("p", { className: "fw-semibold fs-5", children: "Recent Family Information" }), _jsxs("div", { className: "mt-3", children: [_jsxs("div", { className: "d-flex justify-content-between", children: [_jsx("p", { className: "fw-semibold ", children: "Before" }), _jsx(Link, { to: "/family/update-family", className: "text-decoration-none text-success", children: "Edit" })] }), _jsx("img", { src: family, className: "w-100 h-auto", alt: "" })] }), _jsxs("div", { className: "mt-3", children: [_jsxs("div", { className: "d-flex justify-content-between", children: [_jsx("p", { className: "fw-semibold ", children: "Present" }), _jsx(Link, { to: "/family/update-family", className: "text-decoration-none text-success", children: "Edit" })] }), _jsx("img", { src: family, className: "w-100 h-auto", alt: "" })] }), _jsxs("div", { className: "mt-3", children: [_jsxs("div", { className: "d-flex justify-content-between", children: [_jsx("p", { className: "fw-semibold ", children: "Future" }), _jsx(Link, { to: "/family/update-family", className: "text-decoration-none text-success", children: "Edit" })] }), _jsx("img", { src: family, className: "w-100 h-auto", alt: "" })] })] })] })] })] }), _jsx(Footer, {})] }));
};
export default FamilyPortal;
